services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - statistics_db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: monitor_sensors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  statistics_db:
    image: postgres:13
    environment:
      POSTGRES_DB: statistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - statistics-db-data:/var/lib/postgresql/data

volumes:
  db-data:
  statistics-db-data: